const modal=document.getElementById('apply-modal');
let lastFocus=null;
function openModal(){lastFocus=document.activeElement;modal.hidden=false;document.body.style.overflow='hidden';modal.querySelector('.modal-close').focus()}
function closeModal(){modal.hidden=true;document.body.style.overflow='';lastFocus?.focus()}
document.querySelectorAll('.apply-open').forEach(button=>button.addEventListener('click',openModal));
modal.querySelectorAll('.modal-close,.modal-okay,.modal-backdrop').forEach(el=>el.addEventListener('click',closeModal));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!modal.hidden)closeModal();if(event.key==='Tab'&&!modal.hidden){const controls=[...modal.querySelectorAll('button')];if(event.shiftKey&&document.activeElement===controls[0]){controls.at(-1).focus();event.preventDefault()}else if(!event.shiftKey&&document.activeElement===controls.at(-1)){controls[0].focus();event.preventDefault()}}});
const menuButton=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-header nav');
menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню')});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
const teamStage=document.querySelector('.team-stage'),members=[...teamStage.querySelectorAll('.member')],teamDots=document.querySelector('.team-dots');
let selectedMember=0;
function showMember(index){selectedMember=(index+members.length)%members.length;members.forEach((member,i)=>{let offset=(i-selectedMember+members.length)%members.length;if(offset>members.length/2)offset-=members.length;member.dataset.offset=Math.abs(offset)<=2?String(offset):'hidden';member.setAttribute('aria-hidden',String(offset!==0))});[...teamDots.children].forEach((dot,i)=>{dot.classList.toggle('active',i===selectedMember);dot.setAttribute('aria-current',i===selectedMember?'true':'false')})}
members.forEach((member,i)=>{const dot=document.createElement('button');dot.type='button';dot.setAttribute('aria-label',`Показать: ${member.querySelector('h3').textContent}`);dot.addEventListener('click',()=>showMember(i));teamDots.append(dot);member.addEventListener('click',()=>{if(member.dataset.offset==='-1'||member.dataset.offset==='1')showMember(i)})});
teamStage.querySelector('.team-prev').addEventListener('click',()=>showMember(selectedMember-1));teamStage.querySelector('.team-next').addEventListener('click',()=>showMember(selectedMember+1));
teamStage.tabIndex=0;teamStage.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){showMember(selectedMember+(e.key==='ArrowRight'?1:-1));e.preventDefault()}});
let touchStart=null;teamStage.addEventListener('pointerdown',e=>{touchStart=e.clientX});teamStage.addEventListener('pointerup',e=>{if(touchStart!==null&&Math.abs(e.clientX-touchStart)>45)showMember(selectedMember+(e.clientX<touchStart?1:-1));touchStart=null});teamStage.addEventListener('pointercancel',()=>touchStart=null);showMember(0);
document.querySelectorAll('.faq details').forEach(item=>item.addEventListener('toggle',()=>{if(item.open)document.querySelectorAll('.faq details').forEach(other=>{if(other!==item)other.open=false})}));
const sticky=document.querySelector('.sticky-cta');function updateSticky(){const teamRect=teamStage.getBoundingClientRect(),teamOnScreen=teamRect.top<window.innerHeight&&teamRect.bottom>0;sticky.classList.toggle('visible',window.scrollY>520&&window.scrollY<document.documentElement.scrollHeight-window.innerHeight-420&&!teamOnScreen)}window.addEventListener('scroll',updateSticky,{passive:true});updateSticky();
if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const reveal=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('shown');reveal.unobserve(entry.target)}})},{threshold:.1});document.querySelectorAll('.section .center-heading,.about-statement,.about-panel,.career-card,.about-facts,.vacancy-card,.task-grid article,.benefit-grid article,.team-heading,.faq details,.final-cta').forEach(el=>{el.classList.add('reveal');reveal.observe(el)})}
